#include<iostream>
using namespace std;
long long n,m,k,a[100005],b[100005];
int l1,l2,r1,r2;
long long b1mx=LONG_LONG_MAX,b1mn=LONG_LONG_MIN,b2mx=LONG_LONG_MIN,b2mn=LONG_LONG_MAX;
long long a1mx=LONG_LONG_MAX,a1mn=LONG_LONG_MIN,a2mx=LONG_LONG_MIN,a2mn=LONG_LONG_MAX;
bool s11,s12,s13,s21,s22,s23;
int main()
{
	freopen("game.in","r",stdin);
	freopen("game.out","w",stdout);
	cin>>n>>m>>k;
	for(int i=1;i<=n;i++)
	{
		cin>>a[i];
	}
	for(int i=1;i<=m;i++)
	{
		cin>>b[i];
	}
	int o=1;
	for(;o<=k;)
	{
		for(;o<=k;)
		{
			cin>>l1>>r1>>l2>>r2;
			//记录r2正负 
			for(int i=l2;i<=r2;i++)
			{
				if(b[i]>0)
				{
					b2mn=min(b2mn,b[i]);
					b2mx=max(b2mx,b[i]);
					if(s22==0)
					{
						s22=1;
					}
				}
				if(b[i]<0)
				{
					b1mx=min(b1mx,b[i]);
					b1mn=max(b1mn,b[i]);
					if(s23==0)
					{
						s23=1;
					}
				}
				if(b[i]==0&&s21==0)
				{
					s21=1;
				}
				if(s21==1&&s22==1&&s23==1)
				{
					break;
				}
			}
			//记录r1正负 
			for(int i=l1;i<=r1;i++)
			{
				if(a[i]>0)
				{
					a2mn=min(a2mn,a[i]);
					a2mx=max(a2mx,a[i]);
					if(s12==0)
					{
						s12=1;
					}
				}
				if(a[i]<0)
				{
					a1mx=min(a1mx,a[i]);
					a1mn=max(a1mn,a[i]);
					if(s13==0)
					{
						s13=1;
					}
				}
				if(a[i]==0&&s21==0)
				{
					s11=1;
				}
				if(s11==1&&s12==1&&s13==1)
				{
					break;
				}
			}
			if(s23==1&&s22==1)
			{
				if(s11==1)
				{
					cout<<0<<endl;
					o++;
					break;
				}
				else
				{ 
					if(s12==1&&s13==1)
					{
						cout<<max(a2mn*b1mx,a1mn*b2mx)<<endl;o++;break; 
					}
					if(s12==1&&s13==0)
					{
						cout<<a2mn*b1mx<<endl;o++;break;
					}
					if(s12==0&&s13==1)
					{
						cout<<a1mn*b2mx<<endl;o++;break; 
					}
				}
			}
			if(s23==1&&s22==0)
			{
				if(s13==1)
				{
					if(s21==1)
					{
						cout<<0<<endl;o++;break;
					}
					else
					{
						cout<<b1mn*a1mx<<endl;o++;break;
					}
				}
				else
				{
					if(s11==1)
					{
						cout<<0<<endl;o++;break;
					}
					else
					{
						cout<<b1mx*a2mn;o++;break;
					}
				}
			}
			if(s23==0&&s22==1)
			{
				if(s12==1)
				{
					if(s21==1)
					{
						cout<<0<<endl;o++;break;
					}
					else
					{
						cout<<b2mn*a2mx<<endl;o++;break;
					}
				}
				else
				{
					if(s11==1)
					{
						cout<<0<<endl;o++;break;
					}
					else
					{
						cout<<b2mx*a1mn;o++;break;
					}
				}
			}
		}
		a1mx=LONG_LONG_MAX,a1mn=LONG_LONG_MIN,a2mx=LONG_LONG_MIN,a2mn=LONG_LONG_MAX,b1mx=LONG_LONG_MAX,b1mn=LONG_LONG_MIN,b2mx=LONG_LONG_MIN,b2mn=LONG_LONG_MAX;
		s11=0,s12=0,s13=0,s21=0,s22=0,s23=0;
	}
	
}
